packages:
  - packages/*

allowBuilds:
  bcrypt: true
  better-sqlite3: true
  core-js: true
  esbuild: true
  sharp: true
  sqlite3: true
  unrs-resolver: true

patchedDependencies:
  stremthru: patches/stremthru.patch
